# Generated by Django 4.1 on 2022-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photobook',
            fields=[
                ('co_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=500)),
                ('page_details', models.JSONField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
