# Generated by Django 4.1 on 2022-09-19 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photobook',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=500)),
                ('page_details', models.JSONField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('created_at', models.DateField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
