<<<<<<< Updated upstream
# Generated by Django 4.1 on 2022-10-11 09:07
=======
# Generated by Django 4.1 on 2022-10-07 11:15
>>>>>>> Stashed changes

from django.db import migrations, models
<<<<<<< Updated upstream
=======
import django.utils.timezone
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('images', models.FileField(upload_to=Photobook.models.user_directory_path)),
=======
            name='Photobook',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=500)),
                ('page_details', models.JSONField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(verbose_name=django.utils.timezone.now)),
>>>>>>> Stashed changes
            ],
        ),
    ]
