# Generated by Django 4.1 on 2022-10-11 09:07

import Photobook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('images', models.FileField(upload_to=Photobook.models.user_directory_path)),
            ],
        ),
    ]
