# Generated by Django 4.1 on 2022-09-28 07:51

import Photobook.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photobook',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=500)),
                ('page_details', models.JSONField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Photobook.models.user_directory_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sl', to='Photobook.photobook')),
            ],
        ),
    ]
